name: Labeler
on:
  issue_comment:
    types: [created]
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install jq
      run: sudo apt-get install -y jq
    - name: Apply label
      run: |
        echo '${{ github.event.comment.body }}' | grep -q "/label" && \
        echo '${{ github.event }}' 
        LABEL=$(echo '${{ github.event }}' | jq -r '.comment.body' | sed 's/\/label //') && \
#        gh issue edit "${{ github.event.issue.number }}" --add-label "$LABEL" && \
#        gh issue comment "${{ github.event.issue.number }}" --body "Label added."
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
