name: Labeler
on:
  issue_comment:
    types: [created]
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Apply label
      run: |
        echo "${{ github.event.comment.body }}" | grep -q "/label" && \
        gh issue edit "${{ github.event.issue.number }}" --add-label "$(echo '${{ github.event.comment.body }}' | sed 's/\/label //')" && \
        gh pr comment "${{ github.event.issue.number }}" --body "Label added."
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
